// The 24 plans of the validation suite, with the exposition each one carries.
//
// They are presets and not fixtures: the notebook executes them through the
// same interpreter every other cell uses, so a preset that stopped agreeing
// with the suite would show a different verdict here rather than silently
// diverge. The text is read verbatim from ckg/validation-federated/plans/ at
// authoring time.
//
// `blurb` is the plan's own leading comment -- what it says it demonstrates,
// in its author's words rather than a caption written about it afterwards.

export const SECTIONS = {
  verdicts: {
    title: 'The six verdicts',
    lede:
      'Each plan below differs from healthy_chain in one respect, which is what '
      + 'thm:six requires: six configurations of a common baseline, six distinct '
      + 'verdicts. A payload accompanies exactly one of them.',
  },
  translation: {
    title: 'Translation arithmetic',
    lede:
      'Cross-namespace maps are partial, non-injective and non-confluent. '
      + 'Reordering does not recover the loss (thm:reorder), and two routes may '
      + 'return different sets without either being wrong (thm:route-extent).',
  },
  paper: {
    title: "The paper's worked example",
    lede: 'lst:plan of part2-language.tex, executed verbatim.',
  },
  semman4cat: {
    title: 'The SemMan4Cat questions',
    lede:
      "Mark Doerr's five biocatalysis questions, each as a plan. The refusals "
      + 'are the interesting answers: a question this corpus cannot ground is '
      + 'reported as such rather than answered with the nearest available rows.',
  },
  dcat: {
    title: 'Chem-DCAT-AP generic queries',
    lede:
      'The eight generic dataset queries. Three are phrased as scans over an '
      + 'extent a keyed record service does not expose, and thm:static refuses '
      + 'those by name, before contact.',
  },
  other: { title: 'Other plans', lede: '' },
};

export const PLANS = [
  {
    id: 'dcat_g1',
    section: 'dcat',
    blurb:
      'Doerr generic query G1. "Give me all datasets D about a substance with compound C." The easy one, and worth stating plainly so the hard ones are not mistaken for the framework straining. A dataset in Chem-DCAT-AP is what PROV calls an activity: the record of somebody doing something and writing it down. "About a substance with compound C" is then two hops -- which reactions involve the compound, which activities evaluated those reactions -- and both hops run backwards along a stored edge. That backwardness is the whole content of the plan. RXN stores reaction --consumes--> compound; the question supplies the compound. The forward extraction would apply its literal filter to the SUBJECT position, match nothing, and return the empty set -- an answer indistinguishable at the emit boundary from "no dataset is about this compound". So the inverse is a separate predicate with `path` in its requirement, and a deployment whose index runs one way is refused by name instead of answering wrongly.',
    source: `# Doerr generic query G1. "Give me all datasets D about a substance with
# compound C."
#
# The easy one, and worth stating plainly so the hard ones are not mistaken
# for the framework straining. A dataset in Chem-DCAT-AP is what PROV calls
# an activity: the record of somebody doing something and writing it down.
# "About a substance with compound C" is then two hops -- which reactions
# involve the compound, which activities evaluated those reactions -- and
# both hops run backwards along a stored edge.
#
# That backwardness is the whole content of the plan. RXN stores
# reaction --consumes--> compound; the question supplies the compound. The
# forward extraction would apply its literal filter to the SUBJECT position,
# match nothing, and return the empty set -- an answer indistinguishable at
# the emit boundary from "no dataset is about this compound". So the inverse
# is a separate predicate with \`path\` in its requirement, and a deployment
# whose index runs one way is refused by name instead of answering wrongly.
plan dcat_g1 {
  budget 100 requests

  # Which reactions consume catechol. \`consumers_of\` walks \`consumes\`
  # backwards: compound -> reactions.
  let rxns = from RXN
      ask consumers_of("CHEBI:catechol")
      within 20

  # Which activities evaluated those reactions. \`evaluations_of\` walks
  # \`evaluated\` backwards: reaction -> activities.
  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  emit datasets with provenance
}
`,
  },
  {
    id: 'dcat_g2',
    section: 'dcat',
    blurb:
      'Doerr generic query G2. "Give me all datasets D generated by Activity A of type T that evaluated a substance with compound C." G1 with a type constraint on the activity. The interesting part is that the constraint cannot be applied, and the reason is not that PROV is missing a triple -- it is that the question\'s vocabulary and the corpus\'s do not line up, and the plan has to be honest about which of those it is. PROV records what an activity DID: what it evaluated, in which buffer, by whom, on what device. It does not record what an activity IS. There is no `rdf:type` on any ACT: subject in the store. An ontology engineer\'s reflex here is to add one -- declare `ACT:BT1 a chem:MeasurementActivity` -- and that reflex is exactly the failure this framework exists to name. The type would be asserted by whoever wrote the mapping, not observed by whoever ran the experiment, and once it is a triple nothing downstream can tell the two apart. A reasoner then makes it worse by deriving further types from it, each inheriting the standing of a measurement it never had. So this plan retrieves the datasets, and the emitted record says the type constraint is not one this corpus can apply. The alternative -- dropping the unsatisfiable conjunct and returning the same rows silently -- is the defect: a correct answer to G1 presented as an answer to G2.',
    source: `# Doerr generic query G2. "Give me all datasets D generated by Activity A of
# type T that evaluated a substance with compound C."
#
# G1 with a type constraint on the activity. The interesting part is that the
# constraint cannot be applied, and the reason is not that PROV is missing a
# triple -- it is that the question's vocabulary and the corpus's do not line
# up, and the plan has to be honest about which of those it is.
#
# PROV records what an activity DID: what it evaluated, in which buffer, by
# whom, on what device. It does not record what an activity IS. There is no
# \`rdf:type\` on any ACT: subject in the store. An ontology engineer's reflex
# here is to add one -- declare \`ACT:BT1 a chem:MeasurementActivity\` -- and
# that reflex is exactly the failure this framework exists to name. The type
# would be asserted by whoever wrote the mapping, not observed by whoever ran
# the experiment, and once it is a triple nothing downstream can tell the two
# apart. A reasoner then makes it worse by deriving further types from it,
# each inheriting the standing of a measurement it never had.
#
# So this plan retrieves the datasets, and the emitted record says the type
# constraint is not one this corpus can apply. The alternative -- dropping the
# unsatisfiable conjunct and returning the same rows silently -- is the
# defect: a correct answer to G1 presented as an answer to G2.
plan dcat_g2 {
  budget 100 requests

  let rxns = from RXN
      ask consumers_of("CHEBI:catechol")
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  emit datasets with provenance
       as extension of "datasets of activity type T" because vocabulary
}
`,
  },
  {
    id: 'dcat_g3',
    section: 'dcat',
    blurb:
      'Doerr generic query G3. "...the same, with a Bruker Spectrometer set to X." This plan is REFUSED, and no request is issued. That is the result, not a failure to produce one. The clause "with a Bruker Spectrometer" does not name a device. It names a class and asks the instrument service to enumerate its members -- which devices, of all the devices you hold, are Bruker spectrometers. INST is a keyed record service. It answers "tell me about DEV:UV1900i". It has no operation that ranges over its own extent, so it declares `lookup`, `link`, `bind`, `batch` and not `pattern`. thm:static computes Req for the kind test as {pattern, neg}, finds neither in INST\'s declaration, and halts. cor:refuse-before-contact says this happens with requests_issued still 0, and the emitted document names the step, the source, and the two missing features. Compare what the alternative stack does. The ontology has a class BrukerSpectrometer; the reasoner classifies DEV:Bruker-Avance-400 under it; the SPARQL query asks for ?d a :BrukerSpectrometer and returns it. That works -- against a triple store that has already materialised every instrument record. The moment the instrument catalogue is a real service behind a real API, which is what it is at every institute I know of, the federated query either silently omits the instrument leg or the endpoint times out, and in neither case does the answer say so. The refusal here is not the framework being less capable. It is the framework declining to report a number it cannot stand behind, before spending a request to not-earn it.',
    source: `# Doerr generic query G3. "...the same, with a Bruker Spectrometer set to X."
#
# This plan is REFUSED, and no request is issued. That is the result, not a
# failure to produce one.
#
# The clause "with a Bruker Spectrometer" does not name a device. It names a
# class and asks the instrument service to enumerate its members -- which
# devices, of all the devices you hold, are Bruker spectrometers. INST is a
# keyed record service. It answers "tell me about DEV:UV1900i". It has no
# operation that ranges over its own extent, so it declares \`lookup\`, \`link\`,
# \`bind\`, \`batch\` and not \`pattern\`.
#
# thm:static computes Req for the kind test as {pattern, neg}, finds neither
# in INST's declaration, and halts. cor:refuse-before-contact says this
# happens with requests_issued still 0, and the emitted document names the
# step, the source, and the two missing features.
#
# Compare what the alternative stack does. The ontology has a class
# BrukerSpectrometer; the reasoner classifies DEV:Bruker-Avance-400 under it;
# the SPARQL query asks for ?d a :BrukerSpectrometer and returns it. That
# works -- against a triple store that has already materialised every
# instrument record. The moment the instrument catalogue is a real service
# behind a real API, which is what it is at every institute I know of, the
# federated query either silently omits the instrument leg or the endpoint
# times out, and in neither case does the answer say so. The refusal here is
# not the framework being less capable. It is the framework declining to
# report a number it cannot stand behind, before spending a request to
# not-earn it.
plan dcat_g3 {
  budget 100 requests

  let rxns = from RXN
      ask consumers_of("CHEBI:catechol")
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  # The kind test, at the source that cannot perform it. \`typed_as\` requires
  # {pattern, neg}; INST declares {lookup, link, bind, batch}. Both are
  # missing and the check names both.
  let brukers = from INST
      ask typed_as("KIND:bruker-spectrometer")
      within 20

  emit brukers with provenance
}
`,
  },
  {
    id: 'dcat_g4',
    section: 'dcat',
    blurb:
      'Doerr generic query G4. "Give me all datasets D about chemical reaction R that had product P." The named-reaction case, and the one place where a plan and a SPARQL query genuinely coincide in shape. R is named, P is named; the question is whether the store holds the edge, and whether an activity evaluated R. What the plan adds is that the product clause is CHECKED rather than assumed. `identified_as` intersects the named product against the set the previous step actually produced, so a plan naming a product this reaction does not yield returns empty rather than returning the reaction\'s datasets anyway. In a single WHERE block the product triple and the activity triple are conjuncts of one pattern: if the product is wrong the whole block fails and the result is empty -- the same empty as "no activity evaluated it", and the same empty as "R is not in the store". Three questions, one bit.',
    source: `# Doerr generic query G4. "Give me all datasets D about chemical reaction R
# that had product P."
#
# The named-reaction case, and the one place where a plan and a SPARQL query
# genuinely coincide in shape. R is named, P is named; the question is
# whether the store holds the edge, and whether an activity evaluated R.
#
# What the plan adds is that the product clause is CHECKED rather than
# assumed. \`identified_as\` intersects the named product against the set the
# previous step actually produced, so a plan naming a product this reaction
# does not yield returns empty rather than returning the reaction's datasets
# anyway. In a single WHERE block the product triple and the activity triple
# are conjuncts of one pattern: if the product is wrong the whole block fails
# and the result is empty -- the same empty as "no activity evaluated it",
# and the same empty as "R is not in the store". Three questions, one bit.
plan dcat_g4 {
  budget 100 requests

  # What RXN:MT-catechol produces. Forward walk, reaction -> compounds.
  let products = from RXN
      ask reactions_producing("RXN:MT-catechol")
      within 20

  # "that had product P". Membership, gated by the set above: naming guaiacol
  # is not evidence the reaction yields it.
  let has_p = from RXN
      ask identified_as("CHEBI:guaiacol", ?p)
      with ?p in products
      within 20

  # Back to the reaction, then to the activities that evaluated it. This step
  # depends on has_p, so a falsified product clause starves it rather than
  # letting the datasets through on the reaction name alone.
  let rxns = from RXN
      ask producers_of(?p)
      with ?p in has_p
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  emit datasets with provenance
}
`,
  },
  {
    id: 'dcat_g5',
    section: 'dcat',
    blurb:
      'Doerr generic query G5. "Give me all datasets D about chemical reaction R that had a starting material with compound C." The mirror of G4 along the other edge: `consumes` rather than `produces`. Structurally identical, which is worth saying, because it is evidence that the inverse family is a family and not four special cases. One predicate name per direction per edge, each declaring `path`, each with its own lowering that describes the walk it performs. The chemistry is not symmetric even though the graph is. A starting material is something you chose; a product is something you got. The store records both as an edge and cannot tell them apart, which is fine here -- G5 asks about the edge -- and is exactly what makes Q3 unanswerable, where the question is about what you WOULD get.',
    source: `# Doerr generic query G5. "Give me all datasets D about chemical reaction R
# that had a starting material with compound C."
#
# The mirror of G4 along the other edge: \`consumes\` rather than \`produces\`.
# Structurally identical, which is worth saying, because it is evidence that
# the inverse family is a family and not four special cases. One predicate
# name per direction per edge, each declaring \`path\`, each with its own
# lowering that describes the walk it performs.
#
# The chemistry is not symmetric even though the graph is. A starting
# material is something you chose; a product is something you got. The store
# records both as an edge and cannot tell them apart, which is fine here --
# G5 asks about the edge -- and is exactly what makes Q3 unanswerable, where
# the question is about what you WOULD get.
plan dcat_g5 {
  budget 100 requests

  let inputs = from RXN
      ask reactions_consuming("RXN:MT-catechol")
      within 20

  let has_c = from RXN
      ask identified_as("CHEBI:catechol", ?c)
      with ?c in inputs
      within 20

  let rxns = from RXN
      ask consumers_of(?c)
      with ?c in has_c
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  emit datasets with provenance
}
`,
  },
  {
    id: 'dcat_g6',
    section: 'dcat',
    blurb:
      'Doerr generic query G6. "Give me all datasets D about chemical reaction R that had a solvent with compound C." G5\'s shape, and it does not work, for a reason that is not a gap in this fixture but a fact about how reactions get recorded. RXN holds `consumes`. A solvent is not consumed. Neither is a buffer, and PROV holds the buffer as a SETTING of the activity -- BUF:TrisHCl-50mM on ACT:BT1 -- not as a participant of the reaction. So the question\'s "solvent" spans two stores with two different relations, and in neither is it the thing the question calls it. There are two wrong moves available and both are tempting. (1) Answer from `consumes`. This returns SAM and catechol, which are reagents. It is the query dropping a distinction the question was specifically drawing, and the rows come back looking correct. (2) Declare in the ontology that buffer is a subproperty of solvent. Then the reasoner derives BUF:TrisHCl-50mM as a solvent and the query succeeds. But a 50 mM Tris buffer is a solution, and its solvent is water; the derived triple is false, and it is false in a way that is now indistinguishable from a recorded observation. This plan does neither. It retrieves the buffers -- which is real, recorded, and useful -- and states that they are buffers, not solvents, and that the question\'s term has no counterpart here. The gap is `vocabulary`: not a missing value in an existing relation, but an absent relation.',
    source: `# Doerr generic query G6. "Give me all datasets D about chemical reaction R
# that had a solvent with compound C."
#
# G5's shape, and it does not work, for a reason that is not a gap in this
# fixture but a fact about how reactions get recorded.
#
# RXN holds \`consumes\`. A solvent is not consumed. Neither is a buffer, and
# PROV holds the buffer as a SETTING of the activity -- BUF:TrisHCl-50mM on
# ACT:BT1 -- not as a participant of the reaction. So the question's "solvent"
# spans two stores with two different relations, and in neither is it the
# thing the question calls it.
#
# There are two wrong moves available and both are tempting.
#
#   (1) Answer from \`consumes\`. This returns SAM and catechol, which are
#       reagents. It is the query dropping a distinction the question was
#       specifically drawing, and the rows come back looking correct.
#   (2) Declare in the ontology that buffer is a subproperty of solvent. Then
#       the reasoner derives BUF:TrisHCl-50mM as a solvent and the query
#       succeeds. But a 50 mM Tris buffer is a solution, and its solvent is
#       water; the derived triple is false, and it is false in a way that is
#       now indistinguishable from a recorded observation.
#
# This plan does neither. It retrieves the buffers -- which is real, recorded,
# and useful -- and states that they are buffers, not solvents, and that the
# question's term has no counterpart here. The gap is \`vocabulary\`: not a
# missing value in an existing relation, but an absent relation.
plan dcat_g6 {
  budget 100 requests

  let rxns = from RXN
      ask consumers_of("CHEBI:catechol")
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  # What WAS recorded about the medium. Buffer and pH are settings of the
  # activity; the solvent is not recorded at all.
  let media = from PROV
      ask settings_of(?a)
      with ?a in datasets
      within 20

  emit media with provenance
       as extension of "datasets whose solvent has compound C" because vocabulary
}
`,
  },
  {
    id: 'dcat_g7',
    section: 'dcat',
    blurb:
      'Doerr generic query G7. "Give me all datasets D about chemical reaction R that had a catalyst with compound C." The one in this trio that the corpus really does hold, and it is worth putting beside G6 for that reason: the difference between them is not that one question is harder, it is that one relation was recorded and the other was not. Nothing about the question\'s form tells you which. `catalysed_by` links reaction -> enzyme. The question supplies the catalyst and wants the reaction, so this is the inverse again -- `catalysed_reactions` -- and then `evaluations_of` for the third backwards hop to the activity. Three inverse traversals in four steps. Under a triple store all three are free, because the store indexes both ways; the plan declares `path` on each because a service need not, and one that does not is refused rather than answering nothing. The catalyst clause is checked, not assumed: `identified_as` intersects the named enzyme against what actually catalyses the reaction reached. Falsify it and the intersection empties and everything downstream starves, which is the counterfactual run beside this one.',
    source: `# Doerr generic query G7. "Give me all datasets D about chemical reaction R
# that had a catalyst with compound C."
#
# The one in this trio that the corpus really does hold, and it is worth
# putting beside G6 for that reason: the difference between them is not that
# one question is harder, it is that one relation was recorded and the other
# was not. Nothing about the question's form tells you which.
#
# \`catalysed_by\` links reaction -> enzyme. The question supplies the catalyst
# and wants the reaction, so this is the inverse again -- \`catalysed_reactions\`
# -- and then \`evaluations_of\` for the third backwards hop to the activity.
# Three inverse traversals in four steps. Under a triple store all three are
# free, because the store indexes both ways; the plan declares \`path\` on each
# because a service need not, and one that does not is refused rather than
# answering nothing.
#
# The catalyst clause is checked, not assumed: \`identified_as\` intersects the
# named enzyme against what actually catalyses the reaction reached. Falsify
# it and the intersection empties and everything downstream starves, which is
# the counterfactual run beside this one.
plan dcat_g7 {
  budget 100 requests

  # Which reactions this enzyme catalyses. \`catalysed_reactions\` walks
  # \`catalysed_by\` backwards: enzyme -> reactions.
  let cat_rxns = from RXN
      ask catalysed_reactions("ENZ:MT-X")
      within 20

  # And is the enzyme we named actually among the catalysts of what we
  # reached? The clause has to bite, or G7 is G1 with extra words.
  let catalysts = from RXN
      ask enzyme_of(?r)
      with ?r in cat_rxns
      within 20

  let named = from RXN
      ask identified_as("ENZ:MT-X", ?c)
      with ?c in catalysts
      within 20

  # The reactions that survive the check, reached FROM the confirmed catalyst.
  # Binding \`cat_rxns\` here instead would make the check decorative: the
  # counterfactual run beside this one falsifies the catalyst, \`named\` goes
  # empty, and a plan that then binds \`cat_rxns\` still emits two datasets --
  # a correct answer to "datasets about this reaction" dressed as an answer to
  # "datasets about this reaction with THIS catalyst". Every constraint must
  # sit on the path from the question to the payload, or it is not a
  # constraint, it is a comment.
  let confirmed = from RXN
      ask catalysed_reactions(?c)
      with ?c in named
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in confirmed
      within 20

  emit datasets with provenance
}
`,
  },
  {
    id: 'dcat_g8',
    section: 'dcat',
    blurb:
      'Doerr generic query G8. "Give me all datasets D measured with a UV-vis spectrometer and containing a substance with compound C" -- and its variant, "...that had substance S as catalyst and were measured with a Bruker Spectrometer." This plan is REFUSED, and no request is issued -- including the requests for the half of the query that would have succeeded. That is the point of running it after G7. G7\'s compound-and-catalyst legs answer; this query is those legs conjoined with a device-CLASS test, and the class test is G3\'s: "a UV-vis spectrometer" names a kind and asks the instrument service to enumerate its members. INST is keyed. It declares lookup, link, bind, batch and not pattern, and thm:static computes {pattern, neg} for the kind test, finds neither, and halts. Ill-capability is a property of the PLAN, not of a step, so the satisfiable steps do not run either. That is not conservatism; it is the only reading under which the emitted document means anything. If the answerable legs ran and their rows were emitted, the caller would hold two datasets that satisfy the compound constraint and an unenforced device constraint, and no field in the payload would distinguish them from two datasets that satisfy both. The partial result is more dangerous than none, because it looks like an answer. Note what is NOT the reason. There is a UV-vis spectrometer in the catalogue -- DEV:UV1900i, a Shimadzu -- and PROV records ACT:BT3 as measured with it. The data to answer this question exists. The refusal is a capability fact: no source in this federation can be asked "which of your instruments are of kind K", so the constraint cannot be evaluated, and cor:refuse-before-contact says so at requests_issued 0. An ontology stack answers this against a materialised triple store and fails silently the moment the catalogue is a real keyed service -- which, at every institute I know of, it is.',
    source: `# Doerr generic query G8. "Give me all datasets D measured with a UV-vis
# spectrometer and containing a substance with compound C" -- and its variant,
# "...that had substance S as catalyst and were measured with a Bruker
# Spectrometer."
#
# This plan is REFUSED, and no request is issued -- including the requests for
# the half of the query that would have succeeded.
#
# That is the point of running it after G7. G7's compound-and-catalyst legs
# answer; this query is those legs conjoined with a device-CLASS test, and the
# class test is G3's: "a UV-vis spectrometer" names a kind and asks the
# instrument service to enumerate its members. INST is keyed. It declares
# lookup, link, bind, batch and not pattern, and thm:static computes {pattern,
# neg} for the kind test, finds neither, and halts.
#
# Ill-capability is a property of the PLAN, not of a step, so the satisfiable
# steps do not run either. That is not conservatism; it is the only reading
# under which the emitted document means anything. If the answerable legs ran
# and their rows were emitted, the caller would hold two datasets that satisfy
# the compound constraint and an unenforced device constraint, and no field in
# the payload would distinguish them from two datasets that satisfy both. The
# partial result is more dangerous than none, because it looks like an answer.
#
# Note what is NOT the reason. There is a UV-vis spectrometer in the catalogue
# -- DEV:UV1900i, a Shimadzu -- and PROV records ACT:BT3 as measured with it.
# The data to answer this question exists. The refusal is a capability fact:
# no source in this federation can be asked "which of your instruments are of
# kind K", so the constraint cannot be evaluated, and cor:refuse-before-contact
# says so at requests_issued 0. An ontology stack answers this against a
# materialised triple store and fails silently the moment the catalogue is a
# real keyed service -- which, at every institute I know of, it is.
plan dcat_g8 {
  budget 100 requests

  # The answerable half: compound -> reactions -> activities. Never executed.
  let rxns = from RXN
      ask consumers_of("CHEBI:catechol")
      within 20

  let datasets = from PROV
      ask evaluations_of(?r)
      with ?r in rxns
      within 20

  # The device-class test. INST cannot range over its own extent.
  let uvvis = from INST
      ask typed_as("KIND:uv-vis-spectrophotometer")
      within 20

  emit datasets with provenance
}
`,
  },
  {
    id: 'enzymes_in_shared_pathways',
    section: 'paper',
    blurb:
      'lst:plan of part2-language.tex, verbatim.',
    source: `# lst:plan of part2-language.tex, verbatim.
plan enzymes_in_shared_pathways {
  budget 400 requests

  let acids = from CHEBI
      ask descendants_of("CHEBI:35238")
      within 20

  let rxns  = from RHEA
      ask reactions_consuming(?c)
      with ?c in acids
      within 120
      else fail unresolved

  let ecs   = from RHEA
      ask enzyme_of(?r)
      with ?r in rxns
      within 60

  let kids  = map ecs via ec_to_kegg
      expect partial 0.6

  let paths = from KEGG
      ask link("pathway", ?k)
      with ?k in kids
      within 200
      when starved emit partial

  emit paths with provenance
}
`,
  },
  {
    id: 'mark_q1',
    section: 'semman4cat',
    blurb:
      'Doerr Q1. "Which biocatalyst, originating from a bacterium and not a eukaryote, catalyses the transamination of benzylethylamine, and does not have a cysteine in its protein sequence?" One sentence, five steps, three sources, two namespaces. That is the claim: this is not a query with a hard WHERE clause, it is a plan, and writing it as a plan is what makes each of its failure modes separable. The residue clause cannot be a further conjunct of the graph pattern. SEQ holds the sequences and does not declare `pattern`, so it can only scan keys handed to it -- which forces `enzymes` to be computed first and makes the dependency explicit rather than implicit in a join order the endpoint chooses.',
    source: `# Doerr Q1. "Which biocatalyst, originating from a bacterium and not a
# eukaryote, catalyses the transamination of benzylethylamine, and does not
# have a cysteine in its protein sequence?"
#
# One sentence, five steps, three sources, two namespaces. That is the
# claim: this is not a query with a hard WHERE clause, it is a plan, and
# writing it as a plan is what makes each of its failure modes separable.
#
# The residue clause cannot be a further conjunct of the graph pattern. SEQ
# holds the sequences and does not declare \`pattern\`, so it can only scan
# keys handed to it -- which forces \`enzymes\` to be computed first and makes
# the dependency explicit rather than implicit in a join order the endpoint
# chooses.
plan mark_q1 {
  budget 200 requests

  # (b) the transamination. RXN reaches the enzymes by pattern.
  let enzymes = from RXN
      ask enzyme_of("RXN:TA-benzylethylamine")
      within 10

  # (a) bacterium, not eukaryote. \`typed_as\` takes the kind to require and
  # the kind to exclude, so Req carries \`neg\`: this is a negative kind test,
  # and a source that can match a type but not exclude one must say so
  # rather than silently returning the positive half.
  let bacterial = from RXN
      ask typed_as("KIND:bacterial-enzyme", "KIND:eukaryotic-enzyme")
      with ?e in enzymes
      within 10

  let candidates = intersect enzymes bacterial

  # Cross into the sequence namespace. The map is partial by construction:
  # one of the five transaminases has no sequence entry, so retention is
  # 4/5 and the declared expectation says so. If the corpus degrades past
  # that, the step is starved rather than quietly returning less.
  let keyed = map candidates via enz_to_seq
      expect partial 0.75

  # (c) no cysteine. The scan runs at SEQ over the keys it was handed.
  # \`excluding\` requires \`neg\`; the bound set requires \`bind\`; \`pattern\` is
  # NOT required, because this source reaches its literals by key.
  let no_cys = from SEQ
      ask excluding("C", ?k)
      with ?k in keyed
      within 20

  emit no_cys with provenance
}
`,
  },
  {
    id: 'mark_q2',
    section: 'semman4cat',
    blurb:
      'Doerr Q2. "Which buffer composition and pH was used in the biocatalytic methyl transfer using methyl-transferase mt-X of Bacillus subtilis?" The question reads like a lookup and is not one. "Which buffer was used" presupposes a single answer; the store holds two runs of the same reaction with two different buffers, which is the ordinary condition of a laboratory record and not a defect in the data. A query language that returns a set and calls it the answer has silently reinterpreted the question. A plan can say what it did: name the activities, report their settings, and let the reader see that there are two. The organism and enzyme clauses are constraints, and a constraint is only a constraint if the answer depends on it. An earlier draft of this plan named RXN:MT-catechol as a literal and computed the organism clause beside it; the clause was then decoration, because deleting it would not have changed a single emitted row. That is a defect the plan language makes findable and SPARQL does not: in a single WHERE block, a redundant triple pattern and a load-bearing one are the same syntax, and only the plan\'s dependency graph distinguishes a constraint that gates from one that merely accompanies. So the chain here is forced. `runs` binds to `mt_reactions`, `mt_reactions` binds to `bs_enzymes`, and `bs_enzymes` is where "of Bacillus subtilis" enters. Remove the organism step and the plan does not parse.',
    source: `# Doerr Q2. "Which buffer composition and pH was used in the biocatalytic
# methyl transfer using methyl-transferase mt-X of Bacillus subtilis?"
#
# The question reads like a lookup and is not one. "Which buffer was used"
# presupposes a single answer; the store holds two runs of the same reaction
# with two different buffers, which is the ordinary condition of a laboratory
# record and not a defect in the data. A query language that returns a set and
# calls it the answer has silently reinterpreted the question. A plan can say
# what it did: name the activities, report their settings, and let the reader
# see that there are two.
#
# The organism and enzyme clauses are constraints, and a constraint is only a
# constraint if the answer depends on it. An earlier draft of this plan named
# RXN:MT-catechol as a literal and computed the organism clause beside it; the
# clause was then decoration, because deleting it would not have changed a
# single emitted row. That is a defect the plan language makes findable and
# SPARQL does not: in a single WHERE block, a redundant triple pattern and a
# load-bearing one are the same syntax, and only the plan's dependency graph
# distinguishes a constraint that gates from one that merely accompanies.
#
# So the chain here is forced. \`runs\` binds to \`mt_reactions\`, \`mt_reactions\`
# binds to \`bs_enzymes\`, and \`bs_enzymes\` is where "of Bacillus subtilis"
# enters. Remove the organism step and the plan does not parse.
plan mark_q2 {
  budget 200 requests

  # "of Bacillus subtilis". An inverse traversal of \`from_organism\`: the
  # organism sits in the object position of the stored edge, so this is a
  # \`path\` and not a \`pattern\`. RXN declares \`path\`; a source that indexed
  # only forwards would be refused here by name, before any request.
  let bs_enzymes = from RXN
      ask enzymes_from("TAX:Bsubtilis")
      within 10

  # "methyl-transferase mt-X". The organism clause admits two enzymes --
  # B. subtilis contributes both MT-X and TA-Bs to this store -- so something
  # must narrow to the methyl transferase, and here is where the framework
  # reports a limit instead of inventing one.
  #
  # RXN types its enzymes by PROVENANCE (bacterial/eukaryotic), not by EC
  # class. There is no \`KIND:methyltransferase\` to test against. Mark's phrase
  # "methyl-transferase mt-X" therefore does two different kinds of work in
  # one noun phrase: "mt-X" is an identifier this store holds, and
  # "methyl-transferase" is a classification it does not. A reasoner over an
  # EC-aware ontology would discharge both halves; this corpus can discharge
  # only the first. That is a fact about the corpus and not about the
  # question, and the plan says so here rather than in a footnote.
  #
  # The narrowing therefore goes through the identifier. \`identified_as\`
  # returns the named enzyme only if the bound set already holds it, so the
  # organism clause is load-bearing: were MT-X not a B. subtilis enzyme, this
  # step would return the empty set rather than the name it was given. Delete
  # \`bs_enzymes\` and the plan does not parse. An earlier draft of this plan
  # lacked that property and could not be seen to lack it -- in a single
  # SPARQL WHERE block a redundant pattern and a gating one are the same
  # syntax, and only a dependency graph tells them apart.
  let mt_x = from RXN
      ask identified_as("ENZ:MT-X", ?e)
      with ?e in bs_enzymes
      within 10

  # The reaction that enzyme catalyses, reached from the enzyme rather than
  # named. \`catalysed_by\` points reaction --> enzyme, so recovering the
  # reaction from the enzyme is again the inverse.
  let mt_reactions = from RXN
      ask catalysed_reactions(?c)
      with ?c in mt_x
      within 10

  # The runs of that reaction.
  let runs = from PROV
      ask evaluations_of(?r)
      with ?r in mt_reactions
      within 20

  # Their recorded parameters. Every setting is OPTIONAL in the lowered form:
  # an activity that recorded no buffer is returned WITH no buffer, not
  # dropped. "This run recorded no pH" and "there is no such run" are
  # different answers and collapsing them is the one-bit failure again.
  let settings = from PROV
      ask settings_of(?a)
      with ?a in runs
      within 20

  emit settings with provenance
}
`,
  },
  {
    id: 'mark_q3',
    section: 'semman4cat',
    blurb:
      'Doerr Q3. "What is the substrate scope and product range of the Baeyer-Villiger Monooxygenase BVMO-Y?" This plan returns two substrates and two products and then says, in the emitted record, that this is NOT the answer to the question asked. The distinction is the entire point of running it. "Scope" and "range" are modal words. A substrate scope is a claim about what an enzyme WOULD accept, including compounds nobody has put in front of it; the store holds what somebody DID put in front of it and wrote down. Those differ by an inductive step, and no traversal of these triples takes it. A reasoner does not help: a reasoner is sound with respect to its axioms, and there is no axiom of the form "an enzyme that accepts cyclohexanone accepts 2-methylcyclohexanone" -- if there were, it would be a chemical generalisation asserted by whoever wrote the ontology, and the reasoner would be laundering their guess into a derived fact. So the honest output is the extension plus its cardinality plus a statement that the cardinality is a lower bound on nothing, because the question was not about cardinality at all. What SPARQL returns for this question is two rows. What it cannot return is the sentence "these two rows are not a scope", and a reader who receives two rows in answer to a question about scope has been given a wrong answer in the form of a right one. COUNTERFACTUAL NOTE. There is no counterfactual for this plan of the kind that validated Q2 and Q5. Perturbing a constraint here changes which reactions are found; it cannot change whether found-reactions constitute a scope. That the plan\'s own machinery cannot reach the defect is the finding.',
    source: `# Doerr Q3. "What is the substrate scope and product range of the
# Baeyer-Villiger Monooxygenase BVMO-Y?"
#
# This plan returns two substrates and two products and then says, in the
# emitted record, that this is NOT the answer to the question asked. The
# distinction is the entire point of running it.
#
# "Scope" and "range" are modal words. A substrate scope is a claim about
# what an enzyme WOULD accept, including compounds nobody has put in front of
# it; the store holds what somebody DID put in front of it and wrote down.
# Those differ by an inductive step, and no traversal of these triples takes
# it. A reasoner does not help: a reasoner is sound with respect to its
# axioms, and there is no axiom of the form "an enzyme that accepts
# cyclohexanone accepts 2-methylcyclohexanone" -- if there were, it would be
# a chemical generalisation asserted by whoever wrote the ontology, and the
# reasoner would be laundering their guess into a derived fact.
#
# So the honest output is the extension plus its cardinality plus a statement
# that the cardinality is a lower bound on nothing, because the question was
# not about cardinality at all. What SPARQL returns for this question is two
# rows. What it cannot return is the sentence "these two rows are not a
# scope", and a reader who receives two rows in answer to a question about
# scope has been given a wrong answer in the form of a right one.
#
# COUNTERFACTUAL NOTE. There is no counterfactual for this plan of the kind
# that validated Q2 and Q5. Perturbing a constraint here changes which
# reactions are found; it cannot change whether found-reactions constitute a
# scope. That the plan's own machinery cannot reach the defect is the finding.
plan mark_q3 {
  budget 200 requests

  # The reactions this enzyme is recorded as catalysing. Inverse traversal of
  # \`catalysed_by\`: reaction --> enzyme is the stored direction.
  let reactions = from RXN
      ask catalysed_reactions("ENZ:BVMO-Y")
      within 20

  # What went in. Forward from the reaction along \`consumes\`.
  let substrates = from RXN
      ask participants_of(?r)
      with ?r in reactions
      within 20

  # What came out.
  let products = from RXN
      ask reactions_producing(?r)
      with ?r in reactions
      within 20

  emit substrates with provenance
       as extension of "substrate scope" because induction
}
`,
  },
  {
    id: 'mark_q4',
    section: 'semman4cat',
    blurb:
      'Doerr Q4. "What are the expected products of a biocatalytic kinetic resolution reaction with enzyme PFE at pH 9 in HEPES buffer?" "Expected" is the word that decides this plan. Q3 asked for a scope and got the extension; Q4 asks for a PREDICTION, and the difference is that Q4\'s conditions are not in the store at all. PFE has been run once, at pH 7.0 in phosphate. HEPES appears nowhere. pH 9 appears nowhere. There are three things a system can do here and only one of them is honest. (1) Return the products of the pH 7 phosphate run. This is what a query that drops the unsatisfiable conjuncts returns, and it is the worst outcome, because it is a correct answer to a question nobody asked presented as an answer to one somebody did. (2) Return empty. Better, and still ambiguous: "no run matched" and "this enzyme does nothing under these conditions" are different claims and a bare empty set is both. (3) Say that the conditions were never run, name which conjunct failed, and separately report what IS known about the enzyme so the reader can see the distance between the two. This plan does (3). The condition filters run AFTER the enzyme\'s runs are retrieved rather than being folded into the retrieval, which is deliberate: it means the trace shows a non-empty set arriving at the pH filter and an empty set leaving it, so the emitted record can name pH as the conjunct that failed. Folding the conditions into the graph pattern -- the natural SPARQL formulation -- destroys exactly this information, because one WHERE block either matches or does not and cannot report which triple pattern was responsible. Note also that a reasoner makes this case WORSE, not better. Given an axiom that PFE is a lipase and lipases catalyse transesterification, a reasoner will happily derive products at pH 9 that no one has observed, and will present them with the same epistemic standing as a measurement.',
    source: `# Doerr Q4. "What are the expected products of a biocatalytic kinetic
# resolution reaction with enzyme PFE at pH 9 in HEPES buffer?"
#
# "Expected" is the word that decides this plan. Q3 asked for a scope and got
# the extension; Q4 asks for a PREDICTION, and the difference is that Q4's
# conditions are not in the store at all. PFE has been run once, at pH 7.0 in
# phosphate. HEPES appears nowhere. pH 9 appears nowhere.
#
# There are three things a system can do here and only one of them is honest.
#
#   (1) Return the products of the pH 7 phosphate run. This is what a query
#       that drops the unsatisfiable conjuncts returns, and it is the worst
#       outcome, because it is a correct answer to a question nobody asked
#       presented as an answer to one somebody did.
#   (2) Return empty. Better, and still ambiguous: "no run matched" and "this
#       enzyme does nothing under these conditions" are different claims and
#       a bare empty set is both.
#   (3) Say that the conditions were never run, name which conjunct failed,
#       and separately report what IS known about the enzyme so the reader
#       can see the distance between the two.
#
# This plan does (3). The condition filters run AFTER the enzyme's runs are
# retrieved rather than being folded into the retrieval, which is deliberate:
# it means the trace shows a non-empty set arriving at the pH filter and an
# empty set leaving it, so the emitted record can name pH as the conjunct
# that failed. Folding the conditions into the graph pattern -- the natural
# SPARQL formulation -- destroys exactly this information, because one WHERE
# block either matches or does not and cannot report which triple pattern was
# responsible.
#
# Note also that a reasoner makes this case WORSE, not better. Given an
# axiom that PFE is a lipase and lipases catalyse transesterification, a
# reasoner will happily derive products at pH 9 that no one has observed,
# and will present them with the same epistemic standing as a measurement.
plan mark_q4 {
  budget 200 requests

  # The reactions PFE catalyses. Inverse of \`catalysed_by\`.
  let pfe_reactions = from RXN
      ask catalysed_reactions("ENZ:PFE")
      within 20

  # The runs of those reactions, with their recorded conditions.
  let pfe_runs = from PROV
      ask evaluations_of(?r)
      with ?r in pfe_reactions
      within 20

  let conditions = from PROV
      ask settings_of(?a)
      with ?a in pfe_runs
      within 20

  # "at pH 9". The first condition, applied alone so that its failure is
  # attributable. This is where the plan stops.
  let at_ph9 = filter conditions where pH == "9.0"

  # "in HEPES buffer". Never reached, and the trace says so: starved, not
  # empty. Two different reasons for returning nothing, kept apart.
  let in_hepes = filter at_ph9 where buffer == "BUF:HEPES-50mM"

  emit in_hepes with provenance
}
`,
  },
  {
    id: 'mark_q5',
    section: 'semman4cat',
    blurb:
      'Doerr Q5. "With which device was the UV spectrum monitored during biocatalytic transformation BT3 on March 23rd by Yuliia Dikova, and which wavelength was monitored?" This is the question the framework should find EASY, and saying so matters as much as reporting the hard ones. It names an activity, and everything asked for -- device, wavelength, operator, date -- is provenance of that activity. One source, one hop, no translation, no negation. What the plan adds over a lookup is that the three qualifiers are CHECKED rather than trusted. "on March 23rd by Yuliia Dikova" is not decoration in a laboratory record: BT4 also ran on 2026-03-23, and it was run by Doerr on a Bruker. If the plan reached BT3 by name alone and reported its device, it would answer correctly and would also have answered correctly had the date been wrong -- and a reader could not tell the two cases apart. So the date and operator enter as filters over the activity\'s own attributes, and the emitted row is one that survived them.',
    source: `# Doerr Q5. "With which device was the UV spectrum monitored during
# biocatalytic transformation BT3 on March 23rd by Yuliia Dikova, and which
# wavelength was monitored?"
#
# This is the question the framework should find EASY, and saying so matters
# as much as reporting the hard ones. It names an activity, and everything
# asked for -- device, wavelength, operator, date -- is provenance of that
# activity. One source, one hop, no translation, no negation.
#
# What the plan adds over a lookup is that the three qualifiers are CHECKED
# rather than trusted. "on March 23rd by Yuliia Dikova" is not decoration in
# a laboratory record: BT4 also ran on 2026-03-23, and it was run by Doerr on
# a Bruker. If the plan reached BT3 by name alone and reported its device, it
# would answer correctly and would also have answered correctly had the date
# been wrong -- and a reader could not tell the two cases apart. So the date
# and operator enter as filters over the activity's own attributes, and the
# emitted row is one that survived them.
plan mark_q5 {
  budget 100 requests

  # The activities that used any device at all, with their attributes.
  let measured = from PROV
      ask measured_on()
      within 20

  # "during biocatalytic transformation BT3". Membership by name, gated by
  # the set above: an identifier the plan names but PROV does not hold as a
  # measured activity is not returned. Naming BT3 is not evidence BT3 was
  # monitored.
  let bt3 = from PROV
      ask identified_as("ACT:BT3", ?a)
      with ?a in measured
      within 10

  # "on March 23rd". A filter on the attribute the previous step carried.
  let on_date = filter bt3 where date == "2026-03-23"

  # "by Yuliia Dikova". Separate step, not a conjunct: \`filter\` rejects
  # boolean connectives at parse time, and the refusal is deliberate. Two
  # conditions that fail for different reasons should be separable in the
  # trace, and an \`AND\` inside one filter collapses them into a single
  # yes/no that cannot say which half failed.
  let by_ydikova = filter on_date where operator == "PERSON:YDikova"

  emit by_ydikova with provenance
}
`,
  },
  {
    id: 'order_a',
    section: 'translation',
    blurb:
      'Filter before expansion. KEGG:C10 consumes nothing, so dropping it costs no coverage; removing it before the expansion saves the request the expansion would spend on it. The filter names the identifier rather than a label, because chebi2kegg is non-injective -- CHEBI:9 and CHEBI:10 both reach KEGG:C9 -- and the surviving row\'s attributes are whichever preimage was merged last. Only the identifier is reliable after such a map.',
    source: `# Filter before expansion. KEGG:C10 consumes nothing, so dropping it costs no
# coverage; removing it before the expansion saves the request the expansion
# would spend on it. The filter names the identifier rather than a label,
# because chebi2kegg is non-injective -- CHEBI:9 and CHEBI:10 both reach
# KEGG:C9 -- and the surviving row's attributes are whichever preimage was
# merged last. Only the identifier is reliable after such a map.
plan order_a {
  budget 400 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 10

  let kegg  = map acids via chebi2kegg
      expect partial 0.1

  let narrow = filter kegg where _id != "KEGG:C10"

  let rxns  = from rhea
      ask reactions_consuming(?c)
      with ?c in narrow
      within 60

  emit rxns
}
`,
  },
  {
    id: 'order_b',
    section: 'translation',
    blurb:
      'Expand before filtering. Identical coverage to order_a -- the discarded elements contribute nothing downstream -- at a higher request count, because the expansion is charged on the unfiltered input. (V10): the plan language makes the ordering a decision the author states, not one a query planner takes silently.',
    source: `# Expand before filtering. Identical coverage to order_a -- the discarded
# elements contribute nothing downstream -- at a higher request count, because
# the expansion is charged on the unfiltered input. (V10): the plan language
# makes the ordering a decision the author states, not one a query planner
# takes silently.
plan order_b {
  budget 400 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 10

  let kegg  = map acids via chebi2kegg
      expect partial 0.1

  let rxns  = from rhea
      ask reactions_consuming(?c)
      with ?c in kegg
      within 60

  let narrow = filter rxns where _from != "KEGG:C10"

  emit narrow
}
`,
  },
  {
    id: 'routes',
    section: 'translation',
    blurb:
      'lst:routes of part4-translation.tex, verbatim inside a plan wrapper. The listing in the paper is a fragment; the header and budget are the minimum a parseable plan needs and add nothing the fragment did not say.',
    source: `# lst:routes of part4-translation.tex, verbatim inside a plan wrapper.
# The listing in the paper is a fragment; the header and budget are the
# minimum a parseable plan needs and add nothing the fragment did not say.
plan parallel_routes {
  budget 40 requests

  let compounds = from CHEBI
      ask descendants_of("CHEBI:1")
      within 4

  let direct   = map compounds via chebi_to_kegg
  let indirect = map compounds via chebi_to_inchikey
                 then via inchikey_to_kegg

  let both     = union direct indirect
  assert soundness(direct) and soundness(indirect)
  emit divergence(direct, indirect) as resolved_extent
}
`,
  },
  {
    id: 'healthy_chain',
    section: 'verdicts',
    blurb:
      'Identical to starved_chain except the declared expectation. That single difference is what thm:six requires: configurations differing in one respect.',
    source: `# Identical to starved_chain except the declared expectation. That single
# difference is what thm:six requires: configurations differing in one respect.
plan healthy_chain {
  budget 200 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 10

  let kegg  = map acids via chebi2kegg
      expect partial 0.6

  let rxns  = from rhea
      ask reactions_consuming(?c)
      with ?c in kegg
      within 60

  emit rxns
}
`,
  },
  {
    id: 'single_step',
    section: 'verdicts',
    blurb:
      'm = 1. There is no predecessor, so (R1) cannot fire: prop:starve-reachable(a) says starved is unreachable here whatever the fixture does.',
    source: `# m = 1. There is no predecessor, so (R1) cannot fire: prop:starve-reachable(a)
# says starved is unreachable here whatever the fixture does.
plan single_step {
  budget 20 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 8

  emit acids
}
`,
  },
  {
    id: 'empty_answer',
    section: 'verdicts',
    blurb:
      'The request is well-formed, affordable and answered; the corpus simply has no producing reaction for these compounds. (R5) fires, and def:blocker assigns no blocker -- the JSON omits the key entirely.',
    source: `# The request is well-formed, affordable and answered; the corpus simply has
# no producing reaction for these compounds. (R5) fires, and def:blocker
# assigns no blocker -- the JSON omits the key entirely.
plan empty_answer {
  budget 40 requests

  let seeds = from chebi
      ask descendants_of("CHEBI:3")
      within 4

  let kegg  = map seeds via chebi2kegg
      expect partial 0.1

  let none  = from rhea
      ask reactions_producing(?c)
      with ?c in kegg
      within 20

  emit none
}
`,
  },
  {
    id: 'ill_capability',
    section: 'verdicts',
    blurb:
      'The lookup source declares {lookup, link} and NOT pattern. Asking it for a conjunctive pattern is ill-capability, so thm:static refuses before contact: (V1) checks requests_issued is still zero after the refusal.',
    source: `# The lookup source declares {lookup, link} and NOT pattern. Asking it for a
# conjunctive pattern is ill-capability, so thm:static refuses before contact:
# (V1) checks requests_issued is still zero after the refusal.
plan ill_capability {
  budget 100 requests

  let seed = from chebi
      ask descendants_of("CHEBI:1")
      within 4

  let bad  = from enzdb
      ask reactions_consuming(?c)
      with ?c in seed
      within 10

  emit bad
}
`,
  },
  {
    id: 'step_timeout',
    section: 'verdicts',
    blurb:
      'The plan can afford the step; the step\'s own `within` cannot. (R4) fires and def:blocker assigns `engine`, distinct from the `budget` of (R3).',
    source: `# The plan can afford the step; the step's own \`within\` cannot. (R4) fires and
# def:blocker assigns \`engine\`, distinct from the \`budget\` of (R3).
plan step_timeout {
  budget 400 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 10

  let kegg  = map acids via chebi2kegg
      expect partial 0.1

  let rxns  = from rhea
      ask reactions_consuming(?c)
      with ?c in kegg
      within 2

  emit rxns
}
`,
  },
  {
    id: 'budget_trap',
    section: 'verdicts',
    blurb:
      'c_1 = c_2 = 1 and budget = 2, so B >= sum c_i. Step 1 returns cardinality 3, so step 2\'s realised cost is 3 and only 1 request remains: (R3) refuses. prop:necessary-not-sufficient: the c_i are minima over inputs, and the realised input is not the minimising one.',
    source: `# c_1 = c_2 = 1 and budget = 2, so B >= sum c_i. Step 1 returns cardinality 3,
# so step 2's realised cost is 3 and only 1 request remains: (R3) refuses.
# prop:necessary-not-sufficient: the c_i are minima over inputs, and the
# realised input is not the minimising one.
plan budget_trap {
  budget 2 requests

  let roots = from tiny_onto
      ask descendants_of("CHEBI:1")
      within 1

  let rxns  = from tiny_graph
      ask reactions_consuming(?c)
      with ?c in roots
      within 1

  emit rxns
}
`,
  },
  {
    id: 'starved_chain',
    section: 'verdicts',
    blurb:
      'm = 3. The map retains 7/9 end to end but the declared expectation is 0.9, so def:retention-check returns starved; the successor then starves by (R1) and prop:blame terminates at the map step in two hops.',
    source: `# m = 3. The map retains 7/9 end to end but the declared expectation is 0.9,
# so def:retention-check returns starved; the successor then starves by (R1)
# and prop:blame terminates at the map step in two hops.
plan starved_chain {
  budget 200 requests

  let acids = from chebi
      ask descendants_of("CHEBI:1")
      within 10

  let kegg  = map acids via chebi2kegg
      expect partial 0.9

  let rxns  = from rhea
      ask reactions_consuming(?c)
      with ?c in kegg
      within 60

  emit rxns
}
`,
  },
];


export const DEFAULT_PLAN = 'healthy_chain';

export const bySection = (section) => PLANS.filter((p) => p.section === section);

export const byId = (id) => PLANS.find((p) => p.id === id) || null;

export default PLANS;
